name: Python CI/CD

on: [push, pull_request]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Instalacja bibliotek
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Code Review (Linting - Flake8)
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Uruchomienie Testów (Pytest)
        run: pytest


  deploy:
    needs: test-and-lint  
    if: github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    steps:
      - name: Symulacja Wdrażania na serwer
        run: echo "Wdrażanie aplikacji powiodło się"
